cp $PITON_ROOT/build/manycore/mysim/config.v ./config.v
cp $PITON_ROOT/piton/design/chipset/axi_lite_slave_rf/rtl/axi_lite_slave_rf.v ./piton/design/chipset/axi_lite_slave_rf/rtl/axi_lite_slave_rf.v
cp $PITON_ROOT/piton/design/chipset/io_ctrl/rtl/bram_map.v ./piton/design/chipset/io_ctrl/rtl/bram_map.v
cp $PITON_ROOT/piton/design/chipset/io_ctrl/rtl/ciop_iob.v ./piton/design/chipset/io_ctrl/rtl/ciop_iob.v
cp $PITON_ROOT/piton/design/chipset/io_ctrl/rtl/eth_top.v ./piton/design/chipset/io_ctrl/rtl/eth_top.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/components/rtl/io_xbar_one_of_n.tmp.v ./piton/design/chipset/io_xbar/components/rtl/io_xbar_one_of_n.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/components/rtl/io_xbar_one_of_n_plus_3.tmp.v ./piton/design/chipset/io_xbar/components/rtl/io_xbar_one_of_n_plus_3.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/components/rtl/io_xbar_bus_compare_equal.v ./piton/design/chipset/io_xbar/components/rtl/io_xbar_bus_compare_equal.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/components/rtl/io_xbar_flip_bus.v ./piton/design/chipset/io_xbar/components/rtl/io_xbar_flip_bus.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/components/rtl/io_xbar_net_dff.v ./piton/design/chipset/io_xbar/components/rtl/io_xbar_net_dff.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_control.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_control.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_route_request_calc.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_route_request_calc.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_top_16.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_top_16.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_top_4.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_input_top_4.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_output_control.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_output_control.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_output_datapath.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_output_datapath.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_output_top.tmp.v ./piton/design/chipset/io_xbar/dynamic/rtl/io_xbar_output_top.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/common/rtl/io_xbar_space_avail_top.v ./piton/design/chipset/io_xbar/common/rtl/io_xbar_space_avail_top.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/rtl/io_xbar_top.tmp.v ./piton/design/chipset/io_xbar/rtl/io_xbar_top.tmp.v
cp $PITON_ROOT/piton/design/chipset/io_xbar/rtl/io_xbar_top_wrap.tmp.v ./piton/design/chipset/io_xbar/rtl/io_xbar_top_wrap.tmp.v
cp $PITON_ROOT/piton/design/chipset/noc_axilite_bridge/rtl/noc_axilite_bridge.v ./piton/design/chipset/noc_axilite_bridge/rtl/noc_axilite_bridge.v
cp $PITON_ROOT/piton/verif/env/common/fake_mem_ctrl.v ./piton/verif/env/common/fake_mem_ctrl.v
cp -r $PITON_ROOT/piton/verif/env/manycore/../../../design/include ./piton/verif/env/manycore/../../../design/include
cp -r $PITON_ROOT/piton/verif/env/manycore/../../../design/chipset/include ./piton/verif/env/manycore/../../../design/chipset/include
cp -r $PITON_ROOT/piton/verif/env/manycore/ ./piton/verif/env/manycore/
cp $PITON_ROOT/piton/verif/env/manycore/cross_module.tmp.h ./piton/verif/env/manycore/cross_module.tmp.h
cp $PITON_ROOT/piton/verif/env/manycore/my_mon.tmp.v ./piton/verif/env/manycore/my_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/manycore_network_mon.tmp.v ./piton/verif/env/manycore/manycore_network_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/sas_intf.v ./piton/verif/env/manycore/sas_intf.v
cp $PITON_ROOT/piton/verif/env/manycore/monitor.tmp.v ./piton/verif/env/manycore/monitor.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/sas_tasks.tmp.v ./piton/verif/env/manycore/sas_tasks.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/pc_cmp.tmp.v ./piton/verif/env/manycore/pc_cmp.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/sas_task.v ./piton/verif/env/manycore/sas_task.v
cp $PITON_ROOT/piton/verif/env/manycore/l_cache_mon.v ./piton/verif/env/manycore/l_cache_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/thrfsm_mon.v ./piton/verif/env/manycore/thrfsm_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/sparc_pipe_flow.v ./piton/verif/env/manycore/sparc_pipe_flow.v
cp $PITON_ROOT/piton/verif/env/manycore/multicycle_mon.tmp.v ./piton/verif/env/manycore/multicycle_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/dmbr_mon.tmp.v ./piton/verif/env/manycore/dmbr_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/cmp_pcxandcpx.v ./piton/verif/env/manycore/cmp_pcxandcpx.v
cp $PITON_ROOT/piton/verif/env/manycore/tso_mon.tmp.v ./piton/verif/env/manycore/tso_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/lsu_mon.tmp.v ./piton/verif/env/manycore/lsu_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/lsu_mon2.tmp.v ./piton/verif/env/manycore/lsu_mon2.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/exu_mon.v ./piton/verif/env/manycore/exu_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/mask_mon.v ./piton/verif/env/manycore/mask_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/pc_muxsel_mon.v ./piton/verif/env/manycore/pc_muxsel_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/nukeint_mon.v ./piton/verif/env/manycore/nukeint_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/stb_ovfl_mon.v ./piton/verif/env/manycore/stb_ovfl_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/icache_mutex_mon.v ./piton/verif/env/manycore/icache_mutex_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/nc_inv_chk.v ./piton/verif/env/manycore/nc_inv_chk.v
cp $PITON_ROOT/piton/verif/env/manycore/tlu_mon.v ./piton/verif/env/manycore/tlu_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/softint_mon.v ./piton/verif/env/manycore/softint_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/slam_init.tmp.v ./piton/verif/env/manycore/slam_init.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/ciop_iob.tmp.v ./piton/verif/env/manycore/ciop_iob.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/cmp_l15_messages_mon.tmp.v ./piton/verif/env/manycore/cmp_l15_messages_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/jtag_mon.tmp.v ./piton/verif/env/manycore/jtag_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/l2_mon.tmp.v ./piton/verif/env/manycore/l2_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/async_fifo_mon.tmp.v ./piton/verif/env/manycore/async_fifo_mon.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/iob_mon.v ./piton/verif/env/manycore/iob_mon.v
cp $PITON_ROOT/piton/verif/env/manycore/fake_pll.v ./piton/verif/env/manycore/fake_pll.v
cp $PITON_ROOT/piton/verif/env/manycore/manycore_top.tmp.v ./piton/verif/env/manycore/manycore_top.tmp.v
cp $PITON_ROOT/piton/verif/env/manycore/fake_uart.v ./piton/verif/env/manycore/fake_uart.v
cp $PITON_ROOT/piton/design/chip/chip_bridge/rtl/sync_fifo.v ./piton/design/chip/chip_bridge/rtl/sync_fifo.v
cp $PITON_ROOT/piton/design/chip/chip_bridge/rtl/chip_bridge_rcv_32.v ./piton/design/chip/chip_bridge/rtl/chip_bridge_rcv_32.v
cp $PITON_ROOT/piton/design/chip/chip_bridge/rtl/chip_bridge_send_32.v ./piton/design/chip/chip_bridge/rtl/chip_bridge_send_32.v
cp $PITON_ROOT/piton/design/chip/chip_bridge/rtl/chip_net_chooser_32.v ./piton/design/chip/chip_bridge/rtl/chip_net_chooser_32.v
cp $PITON_ROOT/piton/design/chip/chip_bridge/rtl/chip_bridge.v ./piton/design/chip/chip_bridge/rtl/chip_bridge.v
cp $PITON_ROOT/piton/design/common/fpga_bridge/fpga_rcv/rtl/fpga_bridge_rcv_32.v ./piton/design/common/fpga_bridge/fpga_rcv/rtl/fpga_bridge_rcv_32.v
cp $PITON_ROOT/piton/design/common/fpga_bridge/fpga_send/rtl/fpga_bridge_send_32.v ./piton/design/common/fpga_bridge/fpga_send/rtl/fpga_bridge_send_32.v
cp $PITON_ROOT/piton/design/common/fpga_bridge/fpga_send/rtl/fpga_net_chooser_32.v ./piton/design/common/fpga_bridge/fpga_send/rtl/fpga_net_chooser_32.v
cp $PITON_ROOT/piton/design/common/fpga_bridge/rtl/fpga_bridge.v ./piton/design/common/fpga_bridge/rtl/fpga_bridge.v
cp $PITON_ROOT/piton/design/chipset/rtl/chipset.v ./piton/design/chipset/rtl/chipset.v
cp $PITON_ROOT/piton/design/chipset/rtl/chipset_impl.tmp.v ./piton/design/chipset/rtl/chipset_impl.tmp.v
cp $PITON_ROOT/piton/design/chipset/rtl/chipset_impl_noc_power_test.v ./piton/design/chipset/rtl/chipset_impl_noc_power_test.v
cp $PITON_ROOT/piton/design/chipset/rtl/storage_addr_trans.tmp.v ./piton/design/chipset/rtl/storage_addr_trans.tmp.v
cp $PITON_ROOT/piton/design/chipset/rtl/storage_addr_trans_unified.tmp.v ./piton/design/chipset/rtl/storage_addr_trans_unified.tmp.v
cp $PITON_ROOT/piton/design/chipset/rtl/packet_filter.tmp.v ./piton/design/chipset/rtl/packet_filter.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2.v ./piton/design/chip/tile/l2/rtl/l2.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_amo_alu.v ./piton/design/chip/tile/l2/rtl/l2_amo_alu.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_data.v ./piton/design/chip/tile/l2/rtl/l2_data.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_data_wrap.v ./piton/design/chip/tile/l2/rtl/l2_data_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_data_pgen.tmp.v ./piton/design/chip/tile/l2/rtl/l2_data_pgen.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_data_ecc.tmp.v ./piton/design/chip/tile/l2/rtl/l2_data_ecc.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_decoder.v ./piton/design/chip/tile/l2/rtl/l2_decoder.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_dir.v ./piton/design/chip/tile/l2/rtl/l2_dir.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_dir_wrap.v ./piton/design/chip/tile/l2/rtl/l2_dir_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_encoder.v ./piton/design/chip/tile/l2/rtl/l2_encoder.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_mshr.tmp.v ./piton/design/chip/tile/l2/rtl/l2_mshr.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_mshr_decoder.v ./piton/design/chip/tile/l2/rtl/l2_mshr_decoder.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_mshr_wrap.tmp.v ./piton/design/chip/tile/l2/rtl/l2_mshr_wrap.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe1.v ./piton/design/chip/tile/l2/rtl/l2_pipe1.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe1_buf_in.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe1_buf_in.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe1_buf_out.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe1_buf_out.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe1_ctrl.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe1_ctrl.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe1_dpath.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe1_dpath.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe2.v ./piton/design/chip/tile/l2/rtl/l2_pipe2.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe2_buf_in.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe2_buf_in.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe2_ctrl.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe2_ctrl.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_pipe2_dpath.tmp.v ./piton/design/chip/tile/l2/rtl/l2_pipe2_dpath.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_state.tmp.v ./piton/design/chip/tile/l2/rtl/l2_state.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_state_wrap.v ./piton/design/chip/tile/l2/rtl/l2_state_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_tag.v ./piton/design/chip/tile/l2/rtl/l2_tag.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_tag_wrap.v ./piton/design/chip/tile/l2/rtl/l2_tag_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_smc.tmp.v ./piton/design/chip/tile/l2/rtl/l2_smc.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_smc_wrap.v ./piton/design/chip/tile/l2/rtl/l2_smc_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_config_regs.v ./piton/design/chip/tile/l2/rtl/l2_config_regs.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_priority_encoder.tmp.v ./piton/design/chip/tile/l2/rtl/l2_priority_encoder.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_broadcast_counter.v ./piton/design/chip/tile/l2/rtl/l2_broadcast_counter.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/l2_broadcast_counter_wrap.v ./piton/design/chip/tile/l2/rtl/l2_broadcast_counter_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_tag.tmp.v ./piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_tag.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_data.tmp.v ./piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_data.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_state.tmp.v ./piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_state.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_dir.tmp.v ./piton/design/chip/tile/l2/rtl/sram_wrappers/sram_l2_dir.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_control.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_control.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_route_request_calc.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_route_request_calc.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_16.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_16.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_4.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_4.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_control.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_control.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_datapath.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_datapath.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_top.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_top.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_control_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_control_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_route_request_calc_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_route_request_calc_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_16_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_16_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_4_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_input_top_4_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_control_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_control_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_datapath_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_datapath_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_top_para.tmp.v ./piton/design/chip/tile/dynamic_node/dynamic/rtl/dynamic_output_top_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/bus_compare_equal.v ./piton/design/chip/tile/dynamic_node/components/rtl/bus_compare_equal.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/flip_bus.v ./piton/design/chip/tile/dynamic_node/components/rtl/flip_bus.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/one_of_eight.v ./piton/design/chip/tile/dynamic_node/components/rtl/one_of_eight.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/one_of_five.v ./piton/design/chip/tile/dynamic_node/components/rtl/one_of_five.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/one_of_n.tmp.v ./piton/design/chip/tile/dynamic_node/components/rtl/one_of_n.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/one_of_n_plus_3.tmp.v ./piton/design/chip/tile/dynamic_node/components/rtl/one_of_n_plus_3.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/components/rtl/net_dff.v ./piton/design/chip/tile/dynamic_node/components/rtl/net_dff.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/common/rtl/network_input_blk_multi_out.v ./piton/design/chip/tile/dynamic_node/common/rtl/network_input_blk_multi_out.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/common/rtl/space_avail_top.v ./piton/design/chip/tile/dynamic_node/common/rtl/space_avail_top.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top_wrap.v ./piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top.v ./piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top_wrap_para.tmp.v ./piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top_wrap_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top_para.tmp.v ./piton/design/chip/tile/dynamic_node/rtl/dynamic_node_top_para.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/dmbr/rtl/dmbr.tmp.v ./piton/design/chip/tile/dmbr/rtl/dmbr.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/common/srams/rtl/bw_r_rf16x160.v ./piton/design/chip/tile/common/srams/rtl/bw_r_rf16x160.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/credit_to_valrdy.v ./piton/design/chip/tile/common/rtl/credit_to_valrdy.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/valrdy_to_credit.v ./piton/design/chip/tile/common/rtl/valrdy_to_credit.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/flat_id_to_xy.tmp.v ./piton/design/chip/tile/common/rtl/flat_id_to_xy.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/xy_to_flat_id.tmp.v ./piton/design/chip/tile/common/rtl/xy_to_flat_id.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/ucb_bus_in.v ./piton/design/chip/tile/common/rtl/ucb_bus_in.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/ucb_bus_out.v ./piton/design/chip/tile/common/rtl/ucb_bus_out.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/ucb_flow_2buf.v ./piton/design/chip/tile/common/rtl/ucb_flow_2buf.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/ucb_flow_spi.v ./piton/design/chip/tile/common/rtl/ucb_flow_spi.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/ucb_noflow.v ./piton/design/chip/tile/common/rtl/ucb_noflow.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/cluster_header.v ./piton/design/chip/tile/common/rtl/cluster_header.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/cluster_header_sync.v ./piton/design/chip/tile/common/rtl/cluster_header_sync.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/cluster_header_dup.v ./piton/design/chip/tile/common/rtl/cluster_header_dup.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/cluster_header_ctu.v ./piton/design/chip/tile/common/rtl/cluster_header_ctu.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/synchronizer_asr.v ./piton/design/chip/tile/common/rtl/synchronizer_asr.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/synchronizer_asr_dup.v ./piton/design/chip/tile/common/rtl/synchronizer_asr_dup.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/sync_pulse_synchronizer.v ./piton/design/chip/tile/common/rtl/sync_pulse_synchronizer.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/clk_gating_latch.v ./piton/design/chip/tile/common/rtl/clk_gating_latch.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/swrvr_dlib.v ./piton/design/chip/tile/common/rtl/swrvr_dlib.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/mul64.v ./piton/design/chip/tile/common/rtl/mul64.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/swrvr_clib.v ./piton/design/chip/tile/common/rtl/swrvr_clib.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/u1.beh.v ./piton/design/chip/tile/common/rtl/u1.beh.v
cp $PITON_ROOT/piton/design/chip/tile/common/rtl/m1.beh.v ./piton/design/chip/tile/common/rtl/m1.beh.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/../srams/rtl/bw_r_itlb.tmp.v ./piton/design/chip/tile/sparc/rtl/../srams/rtl/bw_r_itlb.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/../srams/rtl/bw_r_dtlb.tmp.v ./piton/design/chip/tile/sparc/rtl/../srams/rtl/bw_r_dtlb.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/../ifu/rtl/sparc_ifu_rndrob.v ./piton/design/chip/tile/sparc/rtl/../ifu/rtl/sparc_ifu_rndrob.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/../lsu/rtl/lsu_dc_parity_gen.v ./piton/design/chip/tile/sparc/rtl/../lsu/rtl/lsu_dc_parity_gen.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_frf.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_frf.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_1rw_128x78.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_1rw_128x78.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_icd.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_icd.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1i_data.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1i_data.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1i_tag.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1i_tag.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_l1i_val.v ./piton/design/chip/tile/sparc/srams/rtl/sram_l1i_val.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_scm.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_scm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_dcd.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_dcd.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1d_data.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1d_data.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_rf32x152b.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_rf32x152b.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1d_tag.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/sram_wrappers/sram_l1d_tag.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/sram_l1d_val.v ./piton/design/chip/tile/sparc/srams/rtl/sram_l1d_val.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_ict.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_ict.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_dct.tmp.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_dct.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/srams/rtl/bw_r_rf32x80.v ./piton/design/chip/tile/sparc/srams/rtl/bw_r_rf32x80.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/mul/rtl/sparc_mul_top_nospu_wrap.v ./piton/design/chip/tile/sparc/mul/rtl/sparc_mul_top_nospu_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/mul/rtl/sparc_mul_top.v ./piton/design/chip/tile/sparc/mul/rtl/sparc_mul_top.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/mul/rtl/sparc_mul_cntl.v ./piton/design/chip/tile/sparc/mul/rtl/sparc_mul_cntl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/mul/rtl/sparc_mul_dp.v ./piton/design/chip/tile/sparc/mul/rtl/sparc_mul_dp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/bw_r_irf/bw_r_irf_register16/rtl/bw_r_irf_register16.v ./piton/design/chip/tile/sparc/exu/bw_r_irf/bw_r_irf_register16/rtl/bw_r_irf_register16.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/bw_r_irf/bw_r_irf_register8/rtl/bw_r_irf_register8.v ./piton/design/chip/tile/sparc/exu/bw_r_irf/bw_r_irf_register8/rtl/bw_r_irf_register8.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/bw_r_irf/common/rtl/bw_r_irf_register.v ./piton/design/chip/tile/sparc/exu/bw_r_irf/common/rtl/bw_r_irf_register.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/bw_r_irf/rtl/bw_r_irf_wrap.v ./piton/design/chip/tile/sparc/exu/bw_r_irf/rtl/bw_r_irf_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/bw_r_irf/rtl/bw_r_irf.v ./piton/design/chip/tile/sparc/exu/bw_r_irf/rtl/bw_r_irf.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_wrap.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_alu.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_alu.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluadder64.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluadder64.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluaddsub.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluaddsub.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_alulogic.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_alulogic.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluor32.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluor32.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluspr.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluspr.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluzcmp64.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_aluzcmp64.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_alu_16eql.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_alu_16eql.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_byp.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_byp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_byp_eccgen.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_byp_eccgen.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_div.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_div.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_div_yreg.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_div_yreg.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_div_32eql.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_div_32eql.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecc.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecc.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecc_dec.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecc_dec.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclbyplog.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclbyplog.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclbyplog_rs1.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclbyplog_rs1.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclccr.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclccr.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclcomp7.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_eclcomp7.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_cnt6.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_cnt6.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_divcntl.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_divcntl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_eccctl.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_eccctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_mdqctl.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_mdqctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_wb.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_ecl_wb.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_reg.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_reg.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rml.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rml.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rml_cwp.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rml_cwp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rml_inc3.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rml_inc3.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rndrob.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_rndrob.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/exu/rtl/sparc_exu_shft.v ./piton/design/chip/tile/sparc/exu/rtl/sparc_exu_shft.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_nospu_wrap.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_nospu_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_ctl.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_ctl_visctl.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_ctl_visctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_dp.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_dp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_part_add32.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_part_add32.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_vis.v ./piton/design/chip/tile/sparc/ffu/rtl/sparc_ffu_vis.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_nospu_wrap.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_nospu_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_incr64.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_incr64.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_mmu_ctl.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_mmu_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_mmu_dp.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_mmu_dp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_pib.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_pib.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_addern_32.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_addern_32.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_prencoder16.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_prencoder16.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_rrobin_picker.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_rrobin_picker.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_tcl.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_tcl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_tdp.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_tdp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_hyperv.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_hyperv.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/tlu_misctl.v ./piton/design/chip/tile/sparc/tlu/rtl/tlu_misctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_dec64.tmp.v ./piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_dec64.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_intctl.v ./piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_intctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_intdp.v ./piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_intdp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_penc64.tmp.v ./piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_penc64.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_zcmp64.v ./piton/design/chip/tile/sparc/tlu/rtl/sparc_tlu_zcmp64.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_nospu_wrap.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_nospu_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_asi_decode.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_asi_decode.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_dcdp.tmp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_dcdp.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_excpctl.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_excpctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_dctl.tmp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_dctl.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_dctldp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_dctldp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_tagdp.tmp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_tagdp.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_tlbdp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_tlbdp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_pcx_qmon.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_pcx_qmon.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_rrobin_picker2.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_rrobin_picker2.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_ctl.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_ctldp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_ctldp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_rwctl.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_rwctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_rwdp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_stb_rwdp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_qctl1.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_qctl1.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_qctl2.tmp.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_qctl2.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_qdp1.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_qdp1.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_qdp2.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_qdp2.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/lsu/rtl/lsu_dcache_lfsr.v ./piton/design/chip/tile/sparc/lsu/rtl/lsu_dcache_lfsr.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_nospu_wrap.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_nospu_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_cmp35.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_cmp35.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_ctr5.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_ctr5.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_dcl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_dcl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_dec.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_dec.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_errctl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_errctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_errdp.tmp.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_errdp.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_fcl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_fcl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_fdp.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_fdp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_wseldp.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_wseldp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_sscan.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_sscan.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_ifqctl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_ifqctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_ifqdp.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_ifqdp.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_imd.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_imd.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_incr46.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_incr46.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_invctl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_invctl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_lfsr5.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_lfsr5.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_lru4.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_lru4.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_milfsm.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_milfsm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_par16.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_par16.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_par32.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_par32.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_par34.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_par34.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_swl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_swl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_swpla.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_swpla.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_thrcmpl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_thrcmpl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_thrfsm.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_thrfsm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_fsm.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_fsm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_stsm.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_stsm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_rtsm.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_rtsm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_htsm.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_htsm.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_counter.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_counter.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_lfsr.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_lfsr.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_shiftreg.v ./piton/design/chip/tile/sparc/ifu/rtl/sparc_ifu_esl_shiftreg.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/sparc_core.v ./piton/design/chip/tile/sparc/rtl/sparc_core.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/sparc.v ./piton/design/chip/tile/sparc/rtl/sparc.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/cpx_spc_rpt.v ./piton/design/chip/tile/sparc/rtl/cpx_spc_rpt.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/cpx_spc_buf.v ./piton/design/chip/tile/sparc/rtl/cpx_spc_buf.v
cp $PITON_ROOT/piton/design/chip/tile/sparc/rtl/cfg_asi.v ./piton/design/chip/tile/sparc/rtl/cfg_asi.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu.v ./piton/design/chip/tile/fpu/rtl/fpu.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_add.v ./piton/design/chip/tile/fpu/rtl/fpu_add.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_add_ctl.v ./piton/design/chip/tile/fpu/rtl/fpu_add_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_add_exp_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_add_exp_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_add_frac_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_add_frac_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_arb.v ./piton/design/chip/tile/fpu/rtl/fpu_arb.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_arb_wrap.v ./piton/design/chip/tile/fpu/rtl/fpu_arb_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_buf.v ./piton/design/chip/tile/fpu/rtl/fpu_buf.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_53b.v ./piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_53b.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_64b.v ./piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_64b.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl1.v ./piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl1.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl2.v ./piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl2.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl3.v ./piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl3.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl4.v ./piton/design/chip/tile/fpu/rtl/fpu_cnt_lead0_lvl4.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_denorm_3b.v ./piton/design/chip/tile/fpu/rtl/fpu_denorm_3b.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_denorm_3to1.v ./piton/design/chip/tile/fpu/rtl/fpu_denorm_3to1.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_denorm_frac.v ./piton/design/chip/tile/fpu/rtl/fpu_denorm_frac.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_div.v ./piton/design/chip/tile/fpu/rtl/fpu_div.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_div_ctl.v ./piton/design/chip/tile/fpu/rtl/fpu_div_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_div_exp_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_div_exp_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_div_frac_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_div_frac_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in.v ./piton/design/chip/tile/fpu/rtl/fpu_in.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in_ctl.v ./piton/design/chip/tile/fpu/rtl/fpu_in_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_in_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_2b.v ./piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_2b.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_3b.v ./piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_3b.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_3to1.v ./piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_3to1.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_frac.v ./piton/design/chip/tile/fpu/rtl/fpu_in2_gt_in1_frac.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_mul.v ./piton/design/chip/tile/fpu/rtl/fpu_mul.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_mul_ctl.v ./piton/design/chip/tile/fpu/rtl/fpu_mul_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_mul_exp_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_mul_exp_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_mul_frac_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_mul_frac_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_out.v ./piton/design/chip/tile/fpu/rtl/fpu_out.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_out_ctl.v ./piton/design/chip/tile/fpu/rtl/fpu_out_ctl.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_out_dp.v ./piton/design/chip/tile/fpu/rtl/fpu_out_dp.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_rptr_macros.v ./piton/design/chip/tile/fpu/rtl/fpu_rptr_macros.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_rptr_groups.v ./piton/design/chip/tile/fpu/rtl/fpu_rptr_groups.v
cp $PITON_ROOT/piton/design/chip/tile/fpu/rtl/fpu_rptr_min_global.v ./piton/design/chip/tile/fpu/rtl/fpu_rptr_min_global.v
cp $PITON_ROOT/piton/design/chip/tile/pico/rtl/picorv32.v ./piton/design/chip/tile/pico/rtl/picorv32.v
cp $PITON_ROOT/piton/design/chip/tile/pico/rtl/pico_reset.v ./piton/design/chip/tile/pico/rtl/pico_reset.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_wrap.v ./piton/design/chip/tile/l15/rtl/l15_wrap.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15.v ./piton/design/chip/tile/l15/rtl/l15.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_mshr.tmp.v ./piton/design/chip/tile/l15/rtl/l15_mshr.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_pipeline.tmp.v ./piton/design/chip/tile/l15/rtl/l15_pipeline.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/rf_l15_lruarray.tmp.v ./piton/design/chip/tile/l15/rtl/rf_l15_lruarray.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/rf_l15_mesi.tmp.v ./piton/design/chip/tile/l15/rtl/rf_l15_mesi.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/rf_l15_lrsc_flag.tmp.v ./piton/design/chip/tile/l15/rtl/rf_l15_lrsc_flag.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/rf_l15_wmt.tmp.v ./piton/design/chip/tile/l15/rtl/rf_l15_wmt.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_cpxencoder.v ./piton/design/chip/tile/l15/rtl/l15_cpxencoder.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/pcx_buffer.v ./piton/design/chip/tile/l15/rtl/pcx_buffer.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/pcx_decoder.v ./piton/design/chip/tile/l15/rtl/pcx_decoder.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/noc1encoder.v ./piton/design/chip/tile/l15/rtl/noc1encoder.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/noc1buffer.tmp.v ./piton/design/chip/tile/l15/rtl/noc1buffer.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/noc3encoder.v ./piton/design/chip/tile/l15/rtl/noc3encoder.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/noc3buffer.v ./piton/design/chip/tile/l15/rtl/noc3buffer.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/noc2decoder.v ./piton/design/chip/tile/l15/rtl/noc2decoder.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/simplenocbuffer.v ./piton/design/chip/tile/l15/rtl/simplenocbuffer.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_csm.tmp.v ./piton/design/chip/tile/l15/rtl/l15_csm.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_hmc.tmp.v ./piton/design/chip/tile/l15/rtl/l15_hmc.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_home_encoder.tmp.v ./piton/design/chip/tile/l15/rtl/l15_home_encoder.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_priority_encoder.tmp.v ./piton/design/chip/tile/l15/rtl/l15_priority_encoder.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/sram_wrappers/sram_l15_tag.tmp.v ./piton/design/chip/tile/l15/rtl/sram_wrappers/sram_l15_tag.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/sram_wrappers/sram_l15_data.tmp.v ./piton/design/chip/tile/l15/rtl/sram_wrappers/sram_l15_data.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/sram_wrappers/sram_l15_hmt.tmp.v ./piton/design/chip/tile/l15/rtl/sram_wrappers/sram_l15_hmt.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/pico_decoder.v ./piton/design/chip/tile/l15/rtl/pico_decoder.v
cp $PITON_ROOT/piton/design/chip/tile/l15/rtl/l15_picoencoder.v ./piton/design/chip/tile/l15/rtl/l15_picoencoder.v
cp $PITON_ROOT/piton/design/chip/tile/rtap/rtl/rtap.v ./piton/design/chip/tile/rtap/rtl/rtap.v
cp $PITON_ROOT/piton/design/chip/tile/rtap/rtl/rtap_ucb_receiver.v ./piton/design/chip/tile/rtap/rtl/rtap_ucb_receiver.v
cp $PITON_ROOT/piton/design/chip/tile/rtap/rtl/rtap_ucb_transmitter.v ./piton/design/chip/tile/rtap/rtl/rtap_ucb_transmitter.v
cp $PITON_ROOT/piton/design/chip/tile/rtl/config_regs.tmp.v ./piton/design/chip/tile/rtl/config_regs.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/rtl/cpx_arbitrator.v ./piton/design/chip/tile/rtl/cpx_arbitrator.v
cp $PITON_ROOT/piton/design/chip/tile/rtl/tile.tmp.v ./piton/design/chip/tile/rtl/tile.tmp.v
cp $PITON_ROOT/piton/design/chip/tile/rtl/ccx_l15_transducer.v ./piton/design/chip/tile/rtl/ccx_l15_transducer.v
cp $PITON_ROOT/piton/design/chip/tile/rtl/pico_l15_transducer.v ./piton/design/chip/tile/rtl/pico_l15_transducer.v
cp $PITON_ROOT/piton/design/chip/jtag/rtl/jtag.v ./piton/design/chip/jtag/rtl/jtag.v
cp $PITON_ROOT/piton/design/chip/jtag/rtl/jtag_interface.v ./piton/design/chip/jtag/rtl/jtag_interface.v
cp $PITON_ROOT/piton/design/chip/jtag/rtl/jtag_interface_tap.v ./piton/design/chip/jtag/rtl/jtag_interface_tap.v
cp $PITON_ROOT/piton/design/chip/jtag/rtl/jtag_ctap.v ./piton/design/chip/jtag/rtl/jtag_ctap.v
cp $PITON_ROOT/piton/design/chip/jtag/rtl/jtag_ucb_receiver.v ./piton/design/chip/jtag/rtl/jtag_ucb_receiver.v
cp $PITON_ROOT/piton/design/chip/jtag/rtl/jtag_ucb_transmitter.v ./piton/design/chip/jtag/rtl/jtag_ucb_transmitter.v
cp $PITON_ROOT/piton/design/chip/pll/rtl/clk_mux.v ./piton/design/chip/pll/rtl/clk_mux.v
cp $PITON_ROOT/piton/design/chip/pll/rtl/clk_se_to_diff.v ./piton/design/chip/pll/rtl/clk_se_to_diff.v
cp $PITON_ROOT/piton/design/chip/pll/rtl/pll_top.v ./piton/design/chip/pll/rtl/pll_top.v
cp $PITON_ROOT/piton/design/chip/rtl/chip.tmp.v ./piton/design/chip/rtl/chip.tmp.v
cp $PITON_ROOT/piton/design/chip/rtl/OCI.v ./piton/design/chip/rtl/OCI.v
cp $PITON_ROOT/piton/design/rtl/system.v ./piton/design/rtl/system.v
cp $PITON_ROOT/piton/design/chipset/include/mc_define.h ./piton/design/chipset/include/mc_define.h
cp $PITON_ROOT/piton/design/chipset/include/uart16550_define.vh ./piton/design/chipset/include/uart16550_define.vh
cp $PITON_ROOT/piton/design/chipset/include/chipset_define.vh ./piton/design/chipset/include/chipset_define.vh
cp $PITON_ROOT/piton/design/common/rtl/chip_rst_seq.v ./piton/design/common/rtl/chip_rst_seq.v
cp $PITON_ROOT/piton/design/common/rtl/alarm_counter.v ./piton/design/common/rtl/alarm_counter.v
cp $PITON_ROOT/piton/design/common/rtl/async_fifo.v ./piton/design/common/rtl/async_fifo.v
cp $PITON_ROOT/piton/design/common/rtl/bram_1rw_wrapper.v ./piton/design/common/rtl/bram_1rw_wrapper.v
cp $PITON_ROOT/piton/design/common/rtl/bram_1r1w_wrapper.v ./piton/design/common/rtl/bram_1r1w_wrapper.v
cp $PITON_ROOT/piton/design/common/rtl/synchronizer.v ./piton/design/common/rtl/synchronizer.v
cp $PITON_ROOT/piton/design/include/define.tmp.h ./piton/design/include/define.tmp.h
cp $PITON_ROOT/piton/design/include/l2.tmp.h ./piton/design/include/l2.tmp.h
cp $PITON_ROOT/piton/design/include/l15.tmp.h ./piton/design/include/l15.tmp.h
cp $PITON_ROOT/piton/design/include/lsu.tmp.h ./piton/design/include/lsu.tmp.h
cp $PITON_ROOT/piton/design/include/ifu.tmp.h ./piton/design/include/ifu.tmp.h
cp -r $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/include/ ./piton/design/chip/tile/ariane/src/common_cells/include/
cp -r $PITON_ROOT/piton/design/chip/tile/ariane/src/util/ ./piton/design/chip/tile/ariane/src/util/
cp $PITON_ROOT/piton/design/chip/tile/ariane/include/riscv_pkg.sv ./piton/design/chip/tile/ariane/include/riscv_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_pkg.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/include/ariane_pkg.sv ./piton/design/chip/tile/ariane/include/ariane_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/deprecated/rrarbiter.sv ./piton/design/chip/tile/ariane/src/common_cells/src/deprecated/rrarbiter.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/deprecated/fifo_v1.sv ./piton/design/chip/tile/ariane/src/common_cells/src/deprecated/fifo_v1.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/deprecated/fifo_v2.sv ./piton/design/chip/tile/ariane/src/common_cells/src/deprecated/fifo_v2.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/fifo_v3.sv ./piton/design/chip/tile/ariane/src/common_cells/src/fifo_v3.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/lfsr_8bit.sv ./piton/design/chip/tile/ariane/src/common_cells/src/lfsr_8bit.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/lzc.sv ./piton/design/chip/tile/ariane/src/common_cells/src/lzc.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/rr_arb_tree.sv ./piton/design/chip/tile/ariane/src/common_cells/src/rr_arb_tree.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/rstgen_bypass.sv ./piton/design/chip/tile/ariane/src/common_cells/src/rstgen_bypass.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/cdc_2phase.sv ./piton/design/chip/tile/ariane/src/common_cells/src/cdc_2phase.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/shift_reg.sv ./piton/design/chip/tile/ariane/src/common_cells/src/shift_reg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/unread.sv ./piton/design/chip/tile/ariane/src/common_cells/src/unread.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/popcount.sv ./piton/design/chip/tile/ariane/src/common_cells/src/popcount.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/common_cells/src/exp_backoff.sv ./piton/design/chip/tile/ariane/src/common_cells/src/exp_backoff.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/register_interface/src/apb_to_reg.sv ./piton/design/chip/tile/ariane/src/register_interface/src/apb_to_reg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/register_interface/src/reg_intf_pkg.sv ./piton/design/chip/tile/ariane/src/register_interface/src/reg_intf_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/register_interface/src/reg_intf.sv ./piton/design/chip/tile/ariane/src/register_interface/src/reg_intf.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_pkg.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_cast_multi.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_cast_multi.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_classifier.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_classifier.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_divsqrt_multi.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_divsqrt_multi.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_fma_multi.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_fma_multi.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_fma.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_fma.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_noncomp.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_noncomp.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_opgroup_block.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_opgroup_block.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_opgroup_fmt_slice.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_opgroup_fmt_slice.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_opgroup_multifmt_slice.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_opgroup_multifmt_slice.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_rounding.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_rounding.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu/src/fpnew_top.sv ./piton/design/chip/tile/ariane/src/fpu/src/fpnew_top.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/axi/src/axi_pkg.sv ./piton/design/chip/tile/ariane/src/axi/src/axi_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/tb/ariane_soc_pkg.sv ./piton/design/chip/tile/ariane/tb/ariane_soc_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/include/ariane_axi_pkg.sv ./piton/design/chip/tile/ariane/include/ariane_axi_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/include/wt_cache_pkg.sv ./piton/design/chip/tile/ariane/include/wt_cache_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/include/axi_intf.sv ./piton/design/chip/tile/ariane/include/axi_intf.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/include/instr_tracer_pkg.sv ./piton/design/chip/tile/ariane/include/instr_tracer_pkg.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/instr_tracer_if.sv ./piton/design/chip/tile/ariane/src/util/instr_tracer_if.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/instr_tracer.sv ./piton/design/chip/tile/ariane/src/util/instr_tracer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/sram.sv ./piton/design/chip/tile/ariane/src/util/sram.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/axi_master_connect.sv ./piton/design/chip/tile/ariane/src/util/axi_master_connect.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/axi_master_connect_rev.sv ./piton/design/chip/tile/ariane/src/util/axi_master_connect_rev.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/axi_slave_connect.sv ./piton/design/chip/tile/ariane/src/util/axi_slave_connect.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/util/axi_slave_connect_rev.sv ./piton/design/chip/tile/ariane/src/util/axi_slave_connect_rev.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpga-support/rtl/SyncSpRamBeNx64.sv ./piton/design/chip/tile/ariane/src/fpga-support/rtl/SyncSpRamBeNx64.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/axi_mem_if/src/axi2mem.sv ./piton/design/chip/tile/ariane/src/axi_mem_if/src/axi2mem.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/tech_cells_generic/src/pulp_clock_gating.sv ./piton/design/chip/tile/ariane/src/tech_cells_generic/src/pulp_clock_gating.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/tech_cells_generic/src/cluster_clock_inverter.sv ./piton/design/chip/tile/ariane/src/tech_cells_generic/src/cluster_clock_inverter.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/tech_cells_generic/src/pulp_clock_mux2.sv ./piton/design/chip/tile/ariane/src/tech_cells_generic/src/pulp_clock_mux2.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/axi_adapter.sv ./piton/design/chip/tile/ariane/src/axi_adapter.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/alu.sv ./piton/design/chip/tile/ariane/src/alu.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/fpu_wrap.sv ./piton/design/chip/tile/ariane/src/fpu_wrap.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/ariane.sv ./piton/design/chip/tile/ariane/src/ariane.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/branch_unit.sv ./piton/design/chip/tile/ariane/src/branch_unit.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/compressed_decoder.sv ./piton/design/chip/tile/ariane/src/compressed_decoder.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/controller.sv ./piton/design/chip/tile/ariane/src/controller.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/csr_buffer.sv ./piton/design/chip/tile/ariane/src/csr_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/csr_regfile.sv ./piton/design/chip/tile/ariane/src/csr_regfile.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/decoder.sv ./piton/design/chip/tile/ariane/src/decoder.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/ex_stage.sv ./piton/design/chip/tile/ariane/src/ex_stage.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/instr_realign.sv ./piton/design/chip/tile/ariane/src/instr_realign.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/frontend/btb.sv ./piton/design/chip/tile/ariane/src/frontend/btb.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/frontend/bht.sv ./piton/design/chip/tile/ariane/src/frontend/bht.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/frontend/ras.sv ./piton/design/chip/tile/ariane/src/frontend/ras.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/frontend/instr_scan.sv ./piton/design/chip/tile/ariane/src/frontend/instr_scan.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/frontend/instr_queue.sv ./piton/design/chip/tile/ariane/src/frontend/instr_queue.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/frontend/frontend.sv ./piton/design/chip/tile/ariane/src/frontend/frontend.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/id_stage.sv ./piton/design/chip/tile/ariane/src/id_stage.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/issue_read_operands.sv ./piton/design/chip/tile/ariane/src/issue_read_operands.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/issue_stage.sv ./piton/design/chip/tile/ariane/src/issue_stage.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/load_unit.sv ./piton/design/chip/tile/ariane/src/load_unit.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/load_store_unit.sv ./piton/design/chip/tile/ariane/src/load_store_unit.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/mmu.sv ./piton/design/chip/tile/ariane/src/mmu.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/mult.sv ./piton/design/chip/tile/ariane/src/mult.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/multiplier.sv ./piton/design/chip/tile/ariane/src/multiplier.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/serdiv.sv ./piton/design/chip/tile/ariane/src/serdiv.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/perf_counters.sv ./piton/design/chip/tile/ariane/src/perf_counters.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/ptw.sv ./piton/design/chip/tile/ariane/src/ptw.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/ariane_regfile_ff.sv ./piton/design/chip/tile/ariane/src/ariane_regfile_ff.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/re_name.sv ./piton/design/chip/tile/ariane/src/re_name.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/scoreboard.sv ./piton/design/chip/tile/ariane/src/scoreboard.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/store_buffer.sv ./piton/design/chip/tile/ariane/src/store_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/amo_buffer.sv ./piton/design/chip/tile/ariane/src/amo_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/store_unit.sv ./piton/design/chip/tile/ariane/src/store_unit.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/tlb.sv ./piton/design/chip/tile/ariane/src/tlb.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/commit_stage.sv ./piton/design/chip/tile/ariane/src/commit_stage.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_ctrl.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_ctrl.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_mem.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_mem.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_missunit.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_missunit.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_wbuffer.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache_wbuffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_dcache.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_icache.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_icache.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_l15_adapter.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_l15_adapter.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/cache_subsystem/wt_cache_subsystem.sv ./piton/design/chip/tile/ariane/src/cache_subsystem/wt_cache_subsystem.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/clint/clint.sv ./piton/design/chip/tile/ariane/src/clint/clint.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/clint/axi_lite_interface.sv ./piton/design/chip/tile/ariane/src/clint/axi_lite_interface.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_csrs.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_csrs.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_mem.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_mem.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_top.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_top.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dmi_cdc.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dmi_cdc.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dmi_jtag.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dmi_jtag.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_sba.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dm_sba.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/src/dmi_jtag_tap.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/src/dmi_jtag_tap.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/riscv-dbg/debug_rom/debug_rom.sv ./piton/design/chip/tile/ariane/src/riscv-dbg/debug_rom/debug_rom.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/openpiton/ariane_verilog_wrap.sv ./piton/design/chip/tile/ariane/openpiton/ariane_verilog_wrap.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/openpiton/riscv_peripherals.sv ./piton/design/chip/tile/ariane/openpiton/riscv_peripherals.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/openpiton/bootrom/baremetal/bootrom.sv ./piton/design/chip/tile/ariane/openpiton/bootrom/baremetal/bootrom.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/openpiton/bootrom/linux/bootrom_linux.sv ./piton/design/chip/tile/ariane/openpiton/bootrom/linux/bootrom_linux.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/rv_plic/rtl/rv_plic_target.sv ./piton/design/chip/tile/ariane/src/rv_plic/rtl/rv_plic_target.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/rv_plic/rtl/rv_plic_gateway.sv ./piton/design/chip/tile/ariane/src/rv_plic/rtl/rv_plic_gateway.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/rv_plic/rtl/plic_regmap.sv ./piton/design/chip/tile/ariane/src/rv_plic/rtl/plic_regmap.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/src/rv_plic/rtl/plic_top.sv ./piton/design/chip/tile/ariane/src/rv_plic/rtl/plic_top.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi2apb/src/axi2apb_wrap.sv ./piton/design/chip/tile/ariane/fpga/src/axi2apb/src/axi2apb_wrap.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi2apb/src/axi2apb.sv ./piton/design/chip/tile/ariane/fpga/src/axi2apb/src/axi2apb.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi2apb/src/axi2apb_64_32.sv ./piton/design/chip/tile/ariane/fpga/src/axi2apb/src/axi2apb_64_32.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_w_buffer.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_w_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_b_buffer.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_b_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_slice_wrap.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_slice_wrap.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_slice.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_slice.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_single_slice.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_single_slice.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_ar_buffer.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_ar_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_r_buffer.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_r_buffer.sv
cp $PITON_ROOT/piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_aw_buffer.sv ./piton/design/chip/tile/ariane/fpga/src/axi_slice/src/axi_aw_buffer.sv
